// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_LabelResult = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 182);
    lv_obj_set_height(ui_Panel2, 69);
    lv_obj_set_x(ui_Panel2, 1);
    lv_obj_set_y(ui_Panel2, 44);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelResult = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelResult, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelResult, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelResult, -1);
    lv_obj_set_y(ui_LabelResult, 55);
    lv_obj_set_align(ui_LabelResult, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_LabelResult, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 132);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 1);
    lv_obj_set_y(ui_Bar1, -110);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -2);
    lv_obj_set_y(ui_Label10, 31);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "LABEL:");

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, -139);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "STATUS");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel2 = NULL;
    ui_LabelResult = NULL;
    ui_Bar1 = NULL;
    ui_Label10 = NULL;
    ui_Label2 = NULL;

}
