// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void measureBeamCmd(lv_event_t * e);
void beamSelectChange(lv_event_t * e);
void toggleChanged(lv_event_t * e);
void homeXaxis(lv_event_t * e);
void homeYaxis(lv_event_t * e);
void stopAllMotors(lv_event_t * e);
void btnPressedUp(lv_event_t * e);
void btnPressedDown(lv_event_t * e);
void btnPressedLeft(lv_event_t * e);
void btnPressedRight(lv_event_t * e);
void saveBeamHome(lv_event_t * e);
void gotoBeamHome(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
