// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 182);
    lv_obj_set_height(ui_Panel2, 69);
    lv_obj_set_x(ui_Panel2, 1);
    lv_obj_set_y(ui_Panel2, 44);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelResult = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelResult, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelResult, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelResult, -1);
    lv_obj_set_y(ui_LabelResult, 55);
    lv_obj_set_align(ui_LabelResult, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_LabelResult, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen3);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 132);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 1);
    lv_obj_set_y(ui_Bar1, -110);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_LabelSpec = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelSpec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpec, 24);
    lv_obj_set_y(ui_LabelSpec, -73);
    lv_obj_set_align(ui_LabelSpec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpec, "?");
    lv_obj_set_style_text_font(ui_LabelSpec, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -48);
    lv_obj_set_y(ui_Label10, -71);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SPEC:");

    ui_LabelPF = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelPF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPF, -2);
    lv_obj_set_y(ui_LabelPF, 28);
    lv_obj_set_align(ui_LabelPF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPF, "----");
    lv_obj_set_style_text_font(ui_LabelPF, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, -139);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "STATUS");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button13, 76);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, -37);
    lv_obj_set_y(ui_Button13, 121);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -37);
    lv_obj_set_y(ui_Label14, 119);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "SETUP");

    ui_Image6 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image6, &ui_img_download_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 173
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 148
    lv_obj_set_x(ui_Image6, 72);
    lv_obj_set_y(ui_Image6, -150);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 30);

    ui_Dropdown2 = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_Dropdown2, "NONE\nC0/1\nC2\nTR1\nTR2");
    lv_obj_set_width(ui_Dropdown2, 85);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 31);
    lv_obj_set_y(ui_Dropdown2, -26);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label19 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -47);
    lv_obj_set_y(ui_Label19, -27);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "FAMILY:");

    ui_Switch2 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_Switch2, 61);
    lv_obj_set_height(ui_Switch2, 40);
    lv_obj_set_x(ui_Switch2, 41);
    lv_obj_set_y(ui_Switch2, 121);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);

}
