// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 46);
    lv_obj_set_height(ui_Button1, 46);
    lv_obj_set_x(ui_Button1, 3);
    lv_obj_set_y(ui_Button1, 61);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 46);
    lv_obj_set_height(ui_Button2, 46);
    lv_obj_set_x(ui_Button2, 2);
    lv_obj_set_y(ui_Button2, 127);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Button2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 46);
    lv_obj_set_height(ui_Button3, 46);
    lv_obj_set_x(ui_Button3, -54);
    lv_obj_set_y(ui_Button3, 88);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Button3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 46);
    lv_obj_set_height(ui_Button4, 46);
    lv_obj_set_x(ui_Button4, 56);
    lv_obj_set_y(ui_Button4, 84);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 4);
    lv_obj_set_y(ui_Label1, 56);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Z+");

    ui_LabelZdown = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelZdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZdown, 1);
    lv_obj_set_y(ui_LabelZdown, 131);
    lv_obj_set_align(ui_LabelZdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZdown, "Z-");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -54);
    lv_obj_set_y(ui_Label3, 85);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "X-");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 56);
    lv_obj_set_y(ui_Label4, 86);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "X+");

    ui_Button5 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button5, 46);
    lv_obj_set_height(ui_Button5, 46);
    lv_obj_set_x(ui_Button5, -51);
    lv_obj_set_y(ui_Button5, -135);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -50);
    lv_obj_set_y(ui_Label6, -135);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "EXIT");

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -57);
    lv_obj_set_y(ui_Label11, lv_pct(42));
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "STALL");
    lv_obj_set_style_radius(ui_Label11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label11, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label11, lv_color_hex(0xD1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button9, 51);
    lv_obj_set_height(ui_Button9, 46);
    lv_obj_set_x(ui_Button9, 52);
    lv_obj_set_y(ui_Button9, -83);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSave = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSave, 54);
    lv_obj_set_y(ui_LabelSave, -83);
    lv_obj_set_align(ui_LabelSave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSave, "SAVE");

    ui_Button10 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button10, 81);
    lv_obj_set_height(ui_Button10, 44);
    lv_obj_set_x(ui_Button10, -28);
    lv_obj_set_y(ui_Button10, -82);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -30);
    lv_obj_set_y(ui_Label15, -83);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "  GO\nHOME");

    ui_Dropdown1 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_Dropdown1, "NONE\nC0/1\nC2\nTR1\nTR2");
    lv_obj_set_width(ui_Dropdown1, 85);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 32);
    lv_obj_set_y(ui_Dropdown1, -136);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 161);
    lv_obj_set_height(ui_Panel1, 70);
    lv_obj_set_x(ui_Panel1, 3);
    lv_obj_set_y(ui_Panel1, -15);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -28);
    lv_obj_set_y(ui_Label5, -11);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "X Home:");

    ui_Label16 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -34);
    lv_obj_set_y(ui_Label16, 6);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "CURPOS Z:");

    ui_Label9 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -33);
    lv_obj_set_y(ui_Label9, -25);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "CURPOS X:");

    ui_LabelXPos = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelXPos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXPos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelXPos, 44);
    lv_obj_set_y(ui_LabelXPos, -25);
    lv_obj_set_align(ui_LabelXPos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelXPos, "?");

    ui_LabelXHome = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelXHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelXHome, 43);
    lv_obj_set_y(ui_LabelXHome, -11);
    lv_obj_set_align(ui_LabelXHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelXHome, "?");

    ui_LabelZPos = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelZPos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZPos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZPos, 44);
    lv_obj_set_y(ui_LabelZPos, 6);
    lv_obj_set_align(ui_LabelZPos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZPos, "?");

    ui_LabelZHome = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelZHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZHome, 44);
    lv_obj_set_y(ui_LabelZHome, 23);
    lv_obj_set_align(ui_LabelZHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZHome, "?");

    ui_Label17 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -26);
    lv_obj_set_y(ui_Label17, 24);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Z Home:");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);

}
